### ISSUE TITLE
Lavalink memory leaks as a "feature"?

### ISSUE THREAD

**Issue by freyacodes** [AmandaDiscord/Volcano#11]
Hi!

The readme of this project accuses Lavalink of breaking protocols and having memory leaks as a feature. What is this about?

The readme is very passive-agressive towards my project. Please be kind :heart:

**Comment by PapiOphidian** [comment]
Those specific lines of text were more referring to my own code. I haven't had memory leak issues with LavaLink, personally, but the voice protocol is difficult and I have seen other projects that *try* to do something similar, but couldn't efficiently manage memory which is why I try to include that memory efficiency is a priority.

I do apologize for the confusion. Massive respect towards LavaLink, which is what caused me to make something protocol-compatible

**Comment by PapiOphidian** [comment]
I'll update the readme to clarify these points and try to be more respectful to the parent project. I will admit some of the wording wasn't written with much thought in mind, but also not written with the intent to hurt the image of LavaLink

**Comment by freyacodes** [comment]
Thanks for clearing that up! It looks like you might have intended to add another line-break but otherwise the change looks good.
