### ISSUE TITLE
Volcano seems to randomly shutdown players

### ISSUE THREAD

**Issue by zabihexes** [AmandaDiscord/Volcano#12]
Volcano shutdowns my player after some time consistently. (Music is still playing at the time when it happens.)
![image](https://user-images.githubusercontent.com/83710104/149951808-cd0b2179-bb04-4553-8e5b-9fcca4f41f45.png)

**Comment by PapiOphidian** [comment]
This seems to be because of connections constantly being created. Possibly due to connection being lost or your code calls connect. It's a bit strange that it's not saying that there was a disconnect which leads me to believe your code is trying to connect multiple times which should not happen. Connect should only be called once unless the node is completely disconnected.

In the event that this is connection instability and your connection to the node is constantly being lost, you should be using the resume feature by sending a resumeKey and a resumeTimeout property in your connection open payload.

**Comment by zabihexes** [comment]
The reconnecting was done by me restarting my bot. It would not behave like that normally.
Also when I connect to "normal" lavalink it works fine. Will try to get resuming to work.

**Comment by zabihexes** [comment]
I thought that this means a problem with the server? Am I wrong?
![image](https://user-images.githubusercontent.com/83710104/149999891-e7d4e3d8-b211-425e-82ef-95ef18a518e5.png)

**Comment by PapiOphidian** [comment]
That is not a problem with the server. That message is only displayed when a connection is closed for any reason. Like I mentioned, if you're facing connection issues, you should be using the resume feature. You should read lavalink's docs for more info on that.

**Comment by zabihexes** [comment]
I see, will look into it. Sorry for bothering you.
