### ISSUE TITLE
Spotify options

### ISSUE THREAD

**Issue by Ayeven** [AmandaDiscord/Volcano#2]
https://www.npmjs.com/package/spotify-url-info

- Get url from spotify for metadata etc
- search it on youtube
- pass youtube link to `youtube-dl`
- ???
- Profit

**Comment by PapiOphidian** [comment]
I have my own code to scrape spotify metadata which I could implement into this project, but that would make going back to lavalink incompatible which could lead to some confusion. I was debating if I should implement or not, but I can give it more thought. I'll leave this issue open for now. Feel free to discuss more or close whenever

**Comment by PapiOphidian** [comment]
I tried to possibly add backwards compatible-ish support for this so that lavalink would reference YouTube as the source, but providing links to Spotify playlists or albums would impose gettings tracks recursively on all tracks in the playlist/album which could cause the Volcano instance's IP to get rate limited.

If you really wanted to provide a Spotify implementation without any extra dependencies, I would reference https://github.com/AmandaDiscord/Amanda/blob/feb402725297fe8f33397fe128c906bd004e7e5d/commands/music/common.js#L756

**Comment by Ayeven** [comment]
After thinking back again on this idea. That would be need to do 2 http request 1 to spotify, 1 to youtube. For personal use, it is fine, but for public, might be not a good idea

**Comment by killer069** [comment]
> https://github.com/AmandaDiscord/Amanda/blob/feb402725297fe8f33397fe128c906bd004e7e5d/commands/music/common.js#L756

Your idea is great but your method is taking more time since it is getting data of actual site. play-dl converts this url to embed url and then get data, so it would get same data but much faster.

Rest depends upon you which method you want to adapt to.

**Comment by PapiOphidian** [comment]
I'll close this issue and either recommend my suggestion Amanda uses or what I've seen other people use which is erela.js with better-erela.js-spotify
