### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by Tomato6966** [AmandaDiscord/Volcano#23]
Here are requests:

-- Lavalink supports youtubemusic, and hopefully deezer soon too --
-> Support Deezer as Audio Source
-> Support YoutubeMusic as Audio Source

-- New lavalink filters allow this: --
-> Support AppleMusic as search option from of Another source
-> Support Spotify as search option from of Another source

**Comment by Tomato6966** [comment]
+ Add a list of what is NOT supported from Lavalink

**Comment by PapiOphidian** [comment]
Thanks for the requests. I already do have a "list" of changes that are different from LavaLink you can find here: https://github.com/AmandaDiscord/Volcano#non-compatible-changes
Some Caveats also lists what sources are supported.

Regardless, I'll work on supporting YouTube Music, Deezer, Apple Music, and Spotify whenever I can.

**Comment by FabrizioCoder** [comment]
> Thanks for the requests. I already do have a "list" of changes that are different from LavaLink you can find here: https://github.com/AmandaDiscord/Volcano#non-compatible-changes Some Caveats also lists what sources are supported.
> 
> Regardless, I'll work on supporting YouTube Music, Deezer, Apple Music, and Spotify whenever I can.

how to search songs in YouTube Music?

**Comment by PapiOphidian** [comment]
You cannot yet. I'm working on it
For the meantime, you can try to match results with `/^(.*)(?!- Topic) - Topic$/`

**Comment by PapiOphidian** [comment]
1.1.8 comes with its own plugin system which you can add support for Apple Music and Deezer yourself. I will not be adding it into Volcano myself due to my desire to remain compliant. I will add plugins to an official list people can refer to should the code quality be sufficient.

As for YouTube music, I've talked with the owner of the YT lib Volcano uses, but progress may be slow getting it out.
You can already pass YouTube Music URLs to Volcano and everything will work just fine, just searching is different.
